# Build stage
FROM node:alpine AS builder

WORKDIR /home/app

COPY package.json .

RUN npm install -g pnpm

RUN pnpm install

COPY . .

RUN pnpm run build

# Production stage
FROM nginx:alpine

COPY --from=builder /home/app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

COPY ssl-certs/ /etc/nginx/ssl-certs/

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]